---
title: UXBlog
baseline: my UX design blog
description: Blog of a french design thinker
keywords: ux, design, thinking, designer, ui
author: Bertrand Berlureau
baseurl: "/"
canonicalurl: true
theme: beb
date:
  format: j F Y
  timezone: Europe/Paris
output:
  formats:
  - name: netlify_redirects
    mediatype: text/plain
    extension: ''
virtualpages:
- path: admin
  title: Content Manager (Netlify CMS)
  layout: admin/index
  output: html
- path: _redirects
  output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
optimize:
  enabled: true
